### ISSUE TITLE
Illiad DocDel tracking table needs to be added

### ISSUE THREAD

**Issue by kgilje** [metridoc/metridoc-rails#86]
There are three types of transactions tracked in Illiad: Borrowing, Lending and DocDel (internal).  There is no tracking information available for DocDel transactions in metridoc.

**Comment by jkiser** [comment]
Karin,

Can you tell me more about what DocDel (internal) means? I'm not clear whether this is in data we're already receiving or that we need to build additional queries.

**Comment by kgilje** [comment]
Hi John,
Here is an example of a doc del transaction:
https://metridoc-rails.library.upenn.edu/admin/illiad_transactions/50633273
It sounds like a new SQL and yml would need to be generated.  I think you could almost copy and paste this:
https://github.com/metridoc/metridoc-rails/blob/master/config/data_sources/upenn_illiad/06_lending.yml
and change the ProcessType to 'Doc Del' instead of 'Lending'.  You may want to double check the key lifecycle points with Tom Bruno.  All the necessary information should be available in the Tracking table.
Hope that helps!
Karin

**Comment by kgilje** [comment]
Handled by Push #137
